---
title: "Plano de ensino do Minicurso de Introdução ao *tidyverse*"
author: "Maurício Vancine"
date: "25/04/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Objetivos
Esse minicurso apresenta os recursos recentes da utilização da manipulação e visualização de dados através do *tidyverse*. O *tidyverse* é um conjunto de pacotes e funções que compartilham uma mesma estrutura visando ajudar os usuários à criar um código eficiente e “organizado”. Os pacotes são focados na organização de dados (leitura, filtragem, organização, seleção e resumo), visualização de dados (ggplot2), programação (purrr), resultados de modelos (broom), além de outros. O curso será teórico-prático, com maior dedicação à realização de exercícios para fixação do conteúdo

## Carga horária
15 horas

## Conteúdo programático
0. Controle de versão, Git e GitHub
1. Introdução ao tidyverse
2. Importar e exportar dados de tabelas (readr, readxl, e writexl)
3. Manejar a estrutura dos dados (tibble, magrittr, tidyr, dplyr, forcats, lubridate e stringr)
4. Visualização de dados e resultados de modelos (ggplot2 e broom)
5. Introdução à programação funcional (purrr)
6. Introdução ao RMarkdown (rmarkdown e knit)

### Bibliografia
Adler, J. (2012). R in a nutshell: A desktop quick reference. O'Reilly Media, Inc.

Allesina, S., & Wilmes, M. (2019). Computing Skills for Biologists: A Toolbox. Princeton University Press.

Beckerman, A. P., Childs, D. Z., & Petchey, O. L. (2017). Getting started with R: an introduction for biologists. Oxford University Press.

Braun, W. J., & Murdoch, D. J. (2016). A first course in statistical programming with R. Cambridge University Press.

Burns, P. (2011). The R inferno. Lulu.com.

Chambers, J. (2008). Software for data analysis: programming with R. Springer Science & Business Media.

Chambers, J. M. (2017). Extending R. Chapman and Hall/CRC.

Campbell, M. (2019). Learn RStudio IDE: Quick, Effective, and Productive Data Science. Springer.

Chang, W. (2018). R graphics cookbook: practical recipes for visualizing data. O'Reilly Media.

Cotton, R. (2013). Learning R: A Step-by-Step Function Guide to Data Analysis. O'Reilly Media, Inc.

Cotton, R. (2017). Testing R Code. Chapman and Hall/CRC.

Crawley, M. J. (2012). The R book. John Wiley & Sons.

Davies, T. M. (2016). The Book of R: A first course in programming and statistics. No Starch Press.

Engel C. 2019. Introduction to R. [https://cengel.github.io/R-intro/](https://cengel.github.io/R-intro/)

Field, A., Miles, J., & Field, Z. (2012). Discovering statistics using R. Sage publications.

Gandrud, C. (2016). Reproducible research with R and R studio. Chapman and Hall/CRC.

Gardener, M. (2012). The essential R reference. John Wiley & Sons.

Gentleman, R. (2008). R programming for bioinformatics. Chapman and Hall/CRC.

Gillespie, C., & Lovelace, R. (2016). Efficient R programming: a practical guide to smarter programming. O'Reilly Media, Inc.

Grolemund, G. (2014). Hands-On Programming with R: Write Your Own Functions and Simulations. O'Reilly Media, Inc.

Hastie, T., Tibshirani, R., & Friedman, J. (2009). The elements of statistical learning: data mining, inference, and prediction. Springer Science & Business Media. [https://web.stanford.edu/~hastie/ElemStatLearn/](https://web.stanford.edu/~hastie/ElemStatLearn/)

Healy, K. (2018). Data visualization: a practical introduction. Princeton University Press.

Hector, A. (2015). The new statistics with R: an introduction for biologists. Oxford University Press.

Hilfiger, J. J. (2015). Graphing Data with R: An Introduction. O'Reilly Media, Inc.

Holmes, S., & Huber, W. (2018). Modern statistics for modern biology. Cambridge University Press. [http://web.stanford.edu/class/bios221/book/index.html](http://web.stanford.edu/class/bios221/book/index.html)

Irizarry, R. A., & Love, M. I. (2016). Data Analysis for the Life Sciences with R. Chapman and Hall/CRC. [http://www.rwdc2.com/files/rafa.pdf](http://www.rwdc2.com/files/rafa.pdf)

Ismay, C., & Kim, A. Y. (2019). Statistical Inference via Data Science: A ModernDive into R and the Tidyverse. CRC Press. [https://moderndive.com/](https://moderndive.com/)

James, G., Witten, D., Hastie, T., & Tibshirani, R. (2013). An introduction to statistical learning (Vol. 112, p. 18). New York: springer. [http://faculty.marshall.usc.edu/gareth-james/ISL/](http://faculty.marshall.usc.edu/gareth-james/ISL/)

Jones, O., Maillardet, R., & Robinson, A. (2014). Introduction to scientific programming and simulation using R. Chapman and Hall/CRC.

Kabacoff, R. (2015). R in Action: Data Analysis and Graphics With R. Greenwich, CT.

Lander, J. P. (2017). R for everyone: advanced analytics and graphics. Pearson Education.

Maindonald, J., & Braun, J. (2010). Data analysis and graphics using R: an example-based approach. Cambridge University Press.

Matloff, N. (2011). The art of R programming: A tour of statistical software design. No Starch Press.

McGrath, M. (2018). R for Data Analysis in easy steps - R Programming essentials. In Easy Steps Limited.

Micheaux, P. L., Drouilhet, R., & Liquet, B. (2013). The R software The R Software: Fundamentals of Programming and Statistical Analysis. Springer Science & Business Media.

Oliveira, P. F., Guerra, S., Mcdonnell, R. (2018). Ciência de dados com R – Introdução. IBPAD. [https://cdr.ibpad.com.br/](https://cdr.ibpad.com.br/)

R Core Team. (2019). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. [https://www.r-project.org/](https://www.r-project.org/)

Racine, J. S. (2012). RStudio: a platform‐independent IDE for R and Sweave. Journal of Applied Econometrics, 27(1), 167-172.

Shahbaba, B. (2012). Biostatistics with R: An Introduction to Statistics Through Biological Data. Springer

Silge, J., & Robinson, D. (2017). Text mining with R: A tidy approach. O'Reilly Media, Inc.

Teetor, P. (2019). R cookbook: proven recipes for data analysis, statistics, and graphics. O'Reilly Media, Inc.

Wickham, H. (2015). R packages: organize, test, document, and share your code. O'Reilly Media, Inc.

Wickham, H. (2016). ggplot2: elegant graphics for data analysis. Springer.

Wickham, H. (2019). Advanced r. Chapman and Hall/CRC.

Wickham, H., & Grolemund, G. (2016). R for data science: import, tidy, transform, visualize, and model data. O'Reilly Media, Inc. [https://r4ds.had.co.nz/](https://r4ds.had.co.nz/)

Wiley, M., & Wiley, J. F. (2016). Advanced R Data Programming and the Cloud. Apress.

Wilke, C. O. (2019). Fundamentals of Data Visualization: A Primer on Making Informative and Compelling Figures. O'Reilly Media. [https://serialmentor.com/dataviz/](https://serialmentor.com/dataviz/)

Xie, Y., Allaire, J. J., & Grolemund, G. (2018). R markdown: The definitive guide. CRC Press. [https://bookdown.org/yihui/rmarkdown/](https://bookdown.org/yihui/rmarkdown/)

Zumel, N., & Mount, J. (2014). Practical data science with R. Manning Publications Co.

Zuur, A., Ieno, E. N., & Meesters, E. (2009). A Beginner's Guide to R. Springer Science & Business Media.