---
title: "Introdução à linguagem R para manipulação e visualização de dados"
format: pdf
editor: visual
---

## Resumo

O minicurso apresentará os fundamentos da linguagem R e do IDE RStudio para a manipulação e visualização de dados através do *tidyverse*. O *tidyverse* é um conjunto de pacotes e funções que compartilham uma mesma estrutura e sintaxe, visando ajudar os usuários a criar um código eficiente e organizado. Os pacotes são focados principalmente na organização (leitura, filtragem, organização, seleção e resumo) e visualização de dados. Serão abordados os seguintes temas: (1) funcionamento da linguagem R, (2) introdução ao tidyverse e (3) visualização de dados. Ao final do minicurso espera-se que os participantes adquiram conhecimentos introdutórios do funcionamento da linguagem através do *tidyverse*, assim como na manipulação e visualização de dados tabulares.

## Carga horária

08 horas

## Repositório do GitHub

[https://github.com/mauriciovancine/workshop-r-introduction](https://github.com/mauriciovancine/workshop-r-introduction)

## Pré-requisitos

Conhecimentos básicos de programação são bem-vindos, mas não são exigidos.

## Ministrante

Maurício Vancine é Bacharel em Ecologia, Mestre em Zoologia e Doutorando em Ecologia, Evolução e Biodiversidade pela UNESP de Rio Claro. Possui experiência em Ecologia Espacial, Ecologia da Paisagem, Modelagem Ecológica e Ecologia de Anfíbios.

Mais informações:

- Website: [https://mauriciovancine.github.io/](https://mauriciovancine.github.io/) 
- Twitter: [https://twitter.com/mauriciovancine](https://twitter.com/mauriciovancine)
- GitHub: [https://github.com/mauriciovancine](https://github.com/mauriciovancine)

## Conteúdo

### 1 Funcionamento da linguagem R (1 h)

1. Linguagem R
1. RStudio
1. Console
1. Scripts
1. Operadores
1. Objetos
1. Funções
1. Pacotes
1. Ajuda
1. Ambiente
1. Citações
1. Principais erros
1. Principal material de estudo

### 2 Introdução ao tidyverse (4 h)

1. Contextualização
1. tidyverse
1. here
1. readr, readxl e writexl
1. tibble
1. magrittr (pipe - %>%)
1. tidyr
1. dplyr

### 3 Visualização de dados (3 h)

1. Contextualização
1. Principais pacotes para gráficos 
1. Grámatica dos gráficos
1. Principais livros e sites 
1. Principais tipos de gráficos 
1. Histograma e Densidade
1. Gráfico de setores
1. Gráfico de barras
1. Gráfico de caixas
1. Gráfico de dispersão
1. Gráfico pareado
1. Combinando gráficos
1. Gráficos animados
1. Gráficos interativos
1. Gráficos usando uma interface

### Bibliografia

Adler J. 2012. R in a nutshell: A desktop quick reference. O'Reilly Media, Inc.

Allesina S, Wilmes M. 2019. Computing Skills for Biologists: A Toolbox. Princeton University Press.

Beckerman AP, Childs DZ, Petchey OL. 2017. Getting started with R: an introduction for biologists. Oxford University Press.

Braun WJ, Murdoch DJ. 2016. A first course in statistical programming with R. Cambridge University Press.

Burns P. 2011. The R inferno. Lulu.com.

Chambers J. 2008. Software for data analysis: programming with R. Springer Science & Business Media.

Chambers JM. 2017. Extending R. Chapman and Hall/CRC.

Campbell M. 2019. Learn RStudio IDE: Quick, Effective, and Productive Data Science. Springer.

Chang W. 2018. R graphics cookbook: practical recipes for visualizing data. O'Reilly Media.

Cotton R. 2013. Learning R: A Step-by-Step Function Guide to Data Analysis. O'Reilly Media, Inc.

Cotton R. 2017. Testing R Code. Chapman and Hall/CRC.

Crawley MJ. 2012. The R book. John Wiley & Sons.

Davies TM. 2016. The Book of R: A first course in programming and statistics. No Starch Press.

Engel C. 2019. Introduction to R. [https://cengel.github.io/R-intro/](https://cengel.github.io/R-intro/)

Field A, Miles J, Field Z. 2012. Discovering statistics using R. Sage publications.

Gandrud C. 2016. Reproducible research with R and R studio. Chapman and Hall/CRC.

Gardener M. 2012. The essential R reference. John Wiley & Sons.

Gentleman R. 2008. R programming for bioinformatics. Chapman and Hall/CRC.

Gillespie C, Lovelace R. 2016. Efficient R programming: a practical guide to smarter programming. O'Reilly Media, Inc.

Grolemund G. 2014. Hands-On Programming with R: Write Your Own Functions and Simulations. O'Reilly Media, Inc.

Hastie T, Tibshirani R, Friedman J. 2009. The elements of statistical learning: data mining, inference, and prediction. Springer Science & Business Media. [https://web.stanford.edu/~hastie/ElemStatLearn/](https://web.stanford.edu/~hastie/ElemStatLearn/)

Healy K. 2018. Data visualization: a practical introduction. Princeton University Press.

Hector A. 2015. The new statistics with R: an introduction for biologists. Oxford University Press.

Hilfiger JJ. 2015. Graphing Data with R: An Introduction. O'Reilly Media, Inc.

Holmes S, Huber W. 2018. Modern statistics for modern biology. Cambridge University Press. [http://web.stanford.edu/class/bios221/book/index.html](http://web.stanford.edu/class/bios221/book/index.html)

Irizarry RA, Love MI. 2016. Data Analysis for the Life Sciences with R. Chapman and Hall/CRC. [http://www.rwdc2.com/files/rafa.pdf](http://www.rwdc2.com/files/rafa.pdf)

Ismay C, Kim AY. 2019. Statistical Inference via Data Science: A ModernDive into R and the Tidyverse. CRC Press. [https://moderndive.com/](https://moderndive.com/)

James G, Witten D, Hastie T,& Tibshirani R. 2013. An introduction to statistical learning (Vol. 112, p. 18). New York: springer. [http://faculty.marshall.usc.edu/gareth-james/ISL/](http://faculty.marshall.usc.edu/gareth-james/ISL/)

Jones O, Maillardet R, Robinson A. 2014. Introduction to scientific programming and simulation using R. Chapman and Hall/CRC.

Kabacoff R. 2015. R in Action: Data Analysis and Graphics With R. Greenwich, CT.

Lander JP. 2017. R for everyone: advanced analytics and graphics. Pearson Education.

Maindonald J, Braun J. 2010. Data analysis and graphics using R: an example-based approach. Cambridge University Press.

Matloff N. 2011. The art of R programming: A tour of statistical software design. No Starch Press.

McGrath M. 2018. R for Data Analysis in easy steps - R Programming essentials. In Easy Steps Limited.

Micheaux PL, Drouilhet R, Liquet B. 2013. The R software The R Software: Fundamentals of Programming and Statistical Analysis. Springer Science & Business Media.

Oliveira PF, Guerra S, Mcdonnell R. 2018. Ciência de dados com R – Introdução. IBPAD. [https://cdr.ibpad.com.br/](https://cdr.ibpad.com.br/)

R Core Team. 2021. R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. [https://www.r-project.org/](https://www.r-project.org/)

Racine JS. 2012. RStudio: a platform‐independent IDE for R and Sweave. Journal of Applied Econometrics, 27(1), 167-172.

Shahbaba B. 2012. Biostatistics with R: An Introduction to Statistics Through Biological Data. Springer

Silge J, Robinson D. 2017. Text mining with R: A tidy approach. O'Reilly Media, Inc.

Teetor P. 2019. R cookbook: proven recipes for data analysis, statistics, and graphics. O'Reilly Media, Inc.

Wickham H. 2015. R packages: organize, test, document, and share your code. O'Reilly Media, Inc.

Wickham H. 2016. ggplot2: elegant graphics for data analysis. Springer.

Wickham H. 2019. Advanced r. Chapman and Hall/CRC.

Wickham H, Grolemund G. 2016. R for data science: import, tidy, transform, visualize, and model data. O'Reilly Media, Inc. [https://r4ds.had.co.nz/](https://r4ds.had.co.nz/)

Wiley M, Wiley, JF. 2016. Advanced R Data Programming and the Cloud. Apress.

Wilke CO. 2019. Fundamentals of Data Visualization: A Primer on Making Informative and Compelling Figures. O'Reilly Media. [https://serialmentor.com/dataviz/](https://serialmentor.com/dataviz/)

Xie Y, Allaire, JJ, Grolemund G. 2018. R markdown: The definitive guide. CRC Press. [https://bookdown.org/yihui/rmarkdown/](https://bookdown.org/yihui/rmarkdown/)

Zumel N, Mount J. 2014. Practical data science with R. Manning Publications Co.

Zuur A, Ieno EN, Meesters E. 2009. A Beginner's Guide to R. Springer Science & Business Media.
